author:
  email: null
  name: An Author
  twitter: null
  url: null
baseurl: /test9-black-jacob
collections:
  annotations:
    output: true
    permalink: /annotations/:path/
  volume_pages:
    output: true
    permalink: /pages/:path/
defaults:
- scope:
    path: ''
    type: volume_pages
  values:
    extra_js:
    - deepzoom.js
    - openseadragon.min.js
    - volume-page.js
    - hammer.min.js
    layout: volume_page
    short_label: p.
- scope:
    path: ''
    type: annotations
  values:
    layout: annotation
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
gems:
- jekyll-sitemap
homepage_image: http://readuxout2in.library.emory.edu/books/emory:b5h9g/pages/emory:gnfvk/single-page/
image_size:
  page:
    height: null
    width: null
  small-thumbnail:
    height: null
    width: null
  thumbnail:
    height: null
    width: null
permalink: pretty
publication_info:
  author: Eddy, A. D. (Ansel Doane), 1798-1875.
  date: '2016'
  editors:
  - Atlanta Studies
  tei_xml: tei.xml
  title: '"Black Jacob," a monument of grace  the life of Jacob Hodges, an African
    Negro, who died in Canandaigua, N.Y., February 1842 , an annotated digital edition'
show_annotation_author: true
source_info:
  author: Eddy, A. D. (Ansel Doane), 1798-1875.
  date: '2011'
  pdf_url: http://readuxout2in.library.emory.edu/books/emory:b5h9g/pdf/#page=2
  title: '"Black Jacob," a monument of grace  the life of Jacob Hodges, an African
    Negro, who died in Canandaigua, N.Y., February 1842 '
  url: http://readuxout2in.library.emory.edu/books/emory:b5h9g/
  via_readux: true
tagline: ', an annotated digital edition'
title: '"Black Jacob," a monument of grace  the life of Jacob Hodges, an African Negro,
  who died in Canandaigua, N.Y., February 1842 '
url: https://jpktest.github.io
version: 0.7
